trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# 🏗️ Build com Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/target'
    artifactName: 'drop'
    publishLocation: 'Container'

- script: |
    echo "Iniciando deploy do artefato gerado..."
    ls $(System.DefaultWorkingDirectory)/target
    # Aqui você poderia rodar o jar ou mover para outro servidor
    # Exemplo: java -jar target/seu-projeto.jar &
    echo "Deploy concluído com sucesso!"
  displayName: 'Etapa de Deploy'
